---
- hosts: db2server
  gather_facts: no
  vars:
    playbook: 
      name: 06_async_mode.yml
  tasks:
    - name: Start role async_mode
      include_role:
        name: async_mode 
        tasks_from: main
...

